CREATE TABLE BENEFICIARY_SUMMARY_08 (		
DESYNPUF_ID	VARCHAR (255)	,
BENE_BIRTH_DT	DATE	,
BENE_DEATH_DT	DATE	,
BENE_SEX_IDENT_CD	VARCHAR (255)	,
BENE_RACE_CD	VARCHAR (255)	,
BENE_ESRD_IND	VARCHAR (255)	,
SP_STATE_CODE	VARCHAR (255)	,
BENE_COUNTY_CD	VARCHAR (255)	,
BENE_HI_CVRAGE_TOT_MONS	VARCHAR (255)	,
BENE_SMI_CVRAGE_TOT_MONS	VARCHAR (255)	,
BENE_HMO_CVRAGE_TOT_MONS	VARCHAR (255)	,
PLAN_CVRG_MOS_NUM	VARCHAR (255)	,
SP_ALZHDMTA	VARCHAR (255)	,
SP_CHF	VARCHAR (255)	,
SP_CHRNKIDN	VARCHAR (255)	,
SP_CNCR	VARCHAR (255)	,
SP_COPD	VARCHAR (255)	,
SP_DEPRESSN	VARCHAR (255)	,
SP_DIABETES	VARCHAR (255)	,
SP_ISCHMCHT	VARCHAR (255)	,
SP_OSTEOPRS	VARCHAR (255)	,
SP_RA_OA	VARCHAR (255)	,
SP_STRKETIA	VARCHAR (255)	,
MEDREIMB_IP	VARCHAR (255)	,
BENRES_IP	VARCHAR (255)	,
PPPYMT_IP	VARCHAR (255)	,
MEDREIMB_OP	VARCHAR (255)	,
BENRES_OP	VARCHAR (255)	,
PPPYMT_OP	VARCHAR (255)	,
MEDREIMB_CAR	VARCHAR (255)	,
BENRES_CAR	VARCHAR (255)	,
PPPYMT_CAR	VARCHAR (255)	);

CREATE TABLE BENEFICIARY_SUMMARY_09 (		
DESYNPUF_ID	VARCHAR (255)	,
BENE_BIRTH_DT	DATE	,
BENE_DEATH_DT	DATE	,
BENE_SEX_IDENT_CD	VARCHAR (255)	,
BENE_RACE_CD	VARCHAR (255)	,
BENE_ESRD_IND	VARCHAR (255)	,
SP_STATE_CODE	VARCHAR (255)	,
BENE_COUNTY_CD	VARCHAR (255)	,
BENE_HI_CVRAGE_TOT_MONS	VARCHAR (255)	,
BENE_SMI_CVRAGE_TOT_MONS	VARCHAR (255)	,
BENE_HMO_CVRAGE_TOT_MONS	VARCHAR (255)	,
PLAN_CVRG_MOS_NUM	VARCHAR (255)	,
SP_ALZHDMTA	VARCHAR (255)	,
SP_CHF	VARCHAR (255)	,
SP_CHRNKIDN	VARCHAR (255)	,
SP_CNCR	VARCHAR (255)	,
SP_COPD	VARCHAR (255)	,
SP_DEPRESSN	VARCHAR (255)	,
SP_DIABETES	VARCHAR (255)	,
SP_ISCHMCHT	VARCHAR (255)	,
SP_OSTEOPRS	VARCHAR (255)	,
SP_RA_OA	VARCHAR (255)	,
SP_STRKETIA	VARCHAR (255)	,
MEDREIMB_IP	VARCHAR (255)	,
BENRES_IP	VARCHAR (255)	,
PPPYMT_IP	VARCHAR (255)	,
MEDREIMB_OP	VARCHAR (255)	,
BENRES_OP	VARCHAR (255)	,
PPPYMT_OP	VARCHAR (255)	,
MEDREIMB_CAR	VARCHAR (255)	,
BENRES_CAR	VARCHAR (255)	,
PPPYMT_CAR	VARCHAR (255)	);

CREATE TABLE BENEFICIARY_SUMMARY_10 (		
DESYNPUF_ID	VARCHAR (255)	,
BENE_BIRTH_DT	DATE	,
BENE_DEATH_DT	DATE	,
BENE_SEX_IDENT_CD	VARCHAR (255)	,
BENE_RACE_CD	VARCHAR (255)	,
BENE_ESRD_IND	VARCHAR (255)	,
SP_STATE_CODE	VARCHAR (255)	,
BENE_COUNTY_CD	VARCHAR (255)	,
BENE_HI_CVRAGE_TOT_MONS	VARCHAR (255)	,
BENE_SMI_CVRAGE_TOT_MONS	VARCHAR (255)	,
BENE_HMO_CVRAGE_TOT_MONS	VARCHAR (255)	,
PLAN_CVRG_MOS_NUM	VARCHAR (255)	,
SP_ALZHDMTA	VARCHAR (255)	,
SP_CHF	VARCHAR (255)	,
SP_CHRNKIDN	VARCHAR (255)	,
SP_CNCR	VARCHAR (255)	,
SP_COPD	VARCHAR (255)	,
SP_DEPRESSN	VARCHAR (255)	,
SP_DIABETES	VARCHAR (255)	,
SP_ISCHMCHT	VARCHAR (255)	,
SP_OSTEOPRS	VARCHAR (255)	,
SP_RA_OA	VARCHAR (255)	,
SP_STRKETIA	VARCHAR (255)	,
MEDREIMB_IP	VARCHAR (255)	,
BENRES_IP	VARCHAR (255)	,
PPPYMT_IP	VARCHAR (255)	,
MEDREIMB_OP	VARCHAR (255)	,
BENRES_OP	VARCHAR (255)	,
PPPYMT_OP	VARCHAR (255)	,
MEDREIMB_CAR	VARCHAR (255)	,
BENRES_CAR	VARCHAR (255)	,
PPPYMT_CAR	VARCHAR (255)	);

CREATE TABLE INPATIENT_CLAIMS (		
DESYNPUF_ID	VARCHAR (255)	,
CLM_ID	VARCHAR (255)	,
SEGMENT	VARCHAR (255)	,
CLM_FROM_DT	DATE	,
CLM_THRU_DT	DATE	,
PRVDR_NUM	VARCHAR (255)	,
CLM_PMT_AMT	VARCHAR (255)	,
NCH_PRMRY_PYR_CLM_PD_AMT	VARCHAR (255)	,
AT_PHYSN_NPI	VARCHAR (255)	,
OP_PHYSN_NPI	VARCHAR (255)	,
OT_PHYSN_NPI	VARCHAR (255)	,
CLM_ADMSN_DT	DATE	,
ADMTNG_ICD9_DGNS_CD	VARCHAR (255)	,
CLM_PASS_THRU_PER_DIEM_AMT	VARCHAR (255)	,
NCH_BENE_IP_DDCTBL_AMT	VARCHAR (255)	,
NCH_BENE_PTA_COINSRNC_LBLTY_AM	VARCHAR (255)	,
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM	VARCHAR (255)	,
CLM_UTLZTN_DAY_CNT	VARCHAR (255)	,
NCH_BENE_DSCHRG_DT	DATE	,
CLM_DRG_CD	VARCHAR (255)	,
ICD9_DGNS_CD_1	VARCHAR (255)	,
ICD9_DGNS_CD_2	VARCHAR (255)	,
ICD9_DGNS_CD_3	VARCHAR (255)	,
ICD9_DGNS_CD_4	VARCHAR (255)	,
ICD9_DGNS_CD_5	VARCHAR (255)	,
ICD9_DGNS_CD_6	VARCHAR (255)	,
ICD9_DGNS_CD_7	VARCHAR (255)	,
ICD9_DGNS_CD_8	VARCHAR (255)	,
ICD9_DGNS_CD_9	VARCHAR (255)	,
ICD9_DGNS_CD_10	VARCHAR (255)	,
ICD9_PRCDR_CD_1	VARCHAR (255)	,
ICD9_PRCDR_CD_2	VARCHAR (255)	,
ICD9_PRCDR_CD_3	VARCHAR (255)	,
ICD9_PRCDR_CD_4	VARCHAR (255)	,
ICD9_PRCDR_CD_5	VARCHAR (255)	,
ICD9_PRCDR_CD_6	VARCHAR (255)	,
HCPCS_CD_1	VARCHAR (255)	,
HCPCS_CD_2	VARCHAR (255)	,
HCPCS_CD_3	VARCHAR (255)	,
HCPCS_CD_4	VARCHAR (255)	,
HCPCS_CD_5	VARCHAR (255)	,
HCPCS_CD_6	VARCHAR (255)	,
HCPCS_CD_7	VARCHAR (255)	,
HCPCS_CD_8	VARCHAR (255)	,
HCPCS_CD_9	VARCHAR (255)	,
HCPCS_CD_10	VARCHAR (255)	,
HCPCS_CD_11	VARCHAR (255)	,
HCPCS_CD_12	VARCHAR (255)	,
HCPCS_CD_13	VARCHAR (255)	,
HCPCS_CD_14	VARCHAR (255)	,
HCPCS_CD_15	VARCHAR (255)	,
HCPCS_CD_16	VARCHAR (255)	,
HCPCS_CD_17	VARCHAR (255)	,
HCPCS_CD_18	VARCHAR (255)	,
HCPCS_CD_19	VARCHAR (255)	,
HCPCS_CD_20	VARCHAR (255)	,
HCPCS_CD_21	VARCHAR (255)	,
HCPCS_CD_22	VARCHAR (255)	,
HCPCS_CD_23	VARCHAR (255)	,
HCPCS_CD_24	VARCHAR (255)	,
HCPCS_CD_25	VARCHAR (255)	,
HCPCS_CD_26	VARCHAR (255)	,
HCPCS_CD_27	VARCHAR (255)	,
HCPCS_CD_28	VARCHAR (255)	,
HCPCS_CD_29	VARCHAR (255)	,
HCPCS_CD_30	VARCHAR (255)	,
HCPCS_CD_31	VARCHAR (255)	,
HCPCS_CD_32	VARCHAR (255)	,
HCPCS_CD_33	VARCHAR (255)	,
HCPCS_CD_34	VARCHAR (255)	,
HCPCS_CD_35	VARCHAR (255)	,
HCPCS_CD_36	VARCHAR (255)	,
HCPCS_CD_37	VARCHAR (255)	,
HCPCS_CD_38	VARCHAR (255)	,
HCPCS_CD_39	VARCHAR (255)	,
HCPCS_CD_40	VARCHAR (255)	,
HCPCS_CD_41	VARCHAR (255)	,
HCPCS_CD_42	VARCHAR (255)	,
HCPCS_CD_43	VARCHAR (255)	,
HCPCS_CD_44	VARCHAR (255)	,
HCPCS_CD_45	VARCHAR (255)	);

CREATE TABLE OUTPATIENT_CLAIMS (		
DESYNPUF_ID	VARCHAR (255)	,
CLM_ID	VARCHAR (255)	,
SEGMENT	VARCHAR (255)	,
CLM_FROM_DT	DATE	,
CLM_THRU_DT	DATE	,
PRVDR_NUM	VARCHAR (255)	,
CLM_PMT_AMT	VARCHAR (255)	,
NCH_PRMRY_PYR_CLM_PD_AMT	VARCHAR (255)	,
AT_PHYSN_NPI	VARCHAR (255)	,
OP_PHYSN_NPI	VARCHAR (255)	,
OT_PHYSN_NPI	VARCHAR (255)	,
NCH_BENE_BLOOD_DDCTBL_LBLTY_AM	VARCHAR (255)	,
ICD9_DGNS_CD_1	VARCHAR (255)	,
ICD9_DGNS_CD_2	VARCHAR (255)	,
ICD9_DGNS_CD_3	VARCHAR (255)	,
ICD9_DGNS_CD_4	VARCHAR (255)	,
ICD9_DGNS_CD_5	VARCHAR (255)	,
ICD9_DGNS_CD_6	VARCHAR (255)	,
ICD9_DGNS_CD_7	VARCHAR (255)	,
ICD9_DGNS_CD_8	VARCHAR (255)	,
ICD9_DGNS_CD_9	VARCHAR (255)	,
ICD9_DGNS_CD_10	VARCHAR (255)	,
ICD9_PRCDR_CD_1	VARCHAR (255)	,
ICD9_PRCDR_CD_2	VARCHAR (255)	,
ICD9_PRCDR_CD_3	VARCHAR (255)	,
ICD9_PRCDR_CD_4	VARCHAR (255)	,
ICD9_PRCDR_CD_5	VARCHAR (255)	,
ICD9_PRCDR_CD_6	VARCHAR (255)	,
NCH_BENE_PTB_DDCTBL_AMT	VARCHAR (255)	,
NCH_BENE_PTB_COINSRNC_AMT	VARCHAR (255)	,
ADMTNG_ICD9_DGNS_CD	VARCHAR (255)	,
HCPCS_CD_1	VARCHAR (255)	,
HCPCS_CD_2	VARCHAR (255)	,
HCPCS_CD_3	VARCHAR (255)	,
HCPCS_CD_4	VARCHAR (255)	,
HCPCS_CD_5	VARCHAR (255)	,
HCPCS_CD_6	VARCHAR (255)	,
HCPCS_CD_7	VARCHAR (255)	,
HCPCS_CD_8	VARCHAR (255)	,
HCPCS_CD_9	VARCHAR (255)	,
HCPCS_CD_10	VARCHAR (255)	,
HCPCS_CD_11	VARCHAR (255)	,
HCPCS_CD_12	VARCHAR (255)	,
HCPCS_CD_13	VARCHAR (255)	,
HCPCS_CD_14	VARCHAR (255)	,
HCPCS_CD_15	VARCHAR (255)	,
HCPCS_CD_16	VARCHAR (255)	,
HCPCS_CD_17	VARCHAR (255)	,
HCPCS_CD_18	VARCHAR (255)	,
HCPCS_CD_19	VARCHAR (255)	,
HCPCS_CD_20	VARCHAR (255)	,
HCPCS_CD_21	VARCHAR (255)	,
HCPCS_CD_22	VARCHAR (255)	,
HCPCS_CD_23	VARCHAR (255)	,
HCPCS_CD_24	VARCHAR (255)	,
HCPCS_CD_25	VARCHAR (255)	,
HCPCS_CD_26	VARCHAR (255)	,
HCPCS_CD_27	VARCHAR (255)	,
HCPCS_CD_28	VARCHAR (255)	,
HCPCS_CD_29	VARCHAR (255)	,
HCPCS_CD_30	VARCHAR (255)	,
HCPCS_CD_31	VARCHAR (255)	,
HCPCS_CD_32	VARCHAR (255)	,
HCPCS_CD_33	VARCHAR (255)	,
HCPCS_CD_34	VARCHAR (255)	,
HCPCS_CD_35	VARCHAR (255)	,
HCPCS_CD_36	VARCHAR (255)	,
HCPCS_CD_37	VARCHAR (255)	,
HCPCS_CD_38	VARCHAR (255)	,
HCPCS_CD_39	VARCHAR (255)	,
HCPCS_CD_40	VARCHAR (255)	,
HCPCS_CD_41	VARCHAR (255)	,
HCPCS_CD_42	VARCHAR (255)	,
HCPCS_CD_43	VARCHAR (255)	,
HCPCS_CD_44	VARCHAR (255)	,
HCPCS_CD_45	VARCHAR (255)	);

CREATE TABLE DGNS_CODES(
DGNS_CD VARCHAR (255),
SHORT_DESC VARCHAR (255)
);

CREATE TABLE PRCDR_CODES(
PRCDR_CD VARCHAR (255),
SHORT_DESC VARCHAR (255)
);

CREATE TABLE STATE_CODES(
STATE_CD VARCHAR (255),
SHORT_DESC VARCHAR (255)
);

--SELECT INTO new table for monthly member costs
-- Step 1: Estimate member-months from beneficiary file
WITH member_months AS (
  SELECT 
    DESYNPUF_ID,
    CASE 
      WHEN BENE_DEATH_DT IS NOT NULL 
           AND DATE_PART('year',BENE_DEATH_DT) = 2010
           THEN DATE_PART('month',BENE_DEATH_DT)
      ELSE 12
    END AS months_enrolled
  FROM beneficiary_summary_10), 

-- Step 2: Standardize inpatient claims
inpatient_costs AS (
  SELECT 
    DESYNPUF_ID,
    DATE_TRUNC('month', CLM_FROM_DT) AS claim_month,
    CLM_PMT_AMT AS allowed_amount,
    'Inpatient' AS claim_type
  FROM inpatient_claims
  WHERE CLM_FROM_DT BETWEEN '2010-01-01' AND '2010-12-31'), 

-- Step 3: Standardize outpatient claims
outpatient_costs AS (
  SELECT 
    DESYNPUF_ID,
    DATE_TRUNC('month', CLM_FROM_DT) AS claim_month,
    CLM_PMT_AMT AS allowed_amount,
    'Outpatient' AS claim_type
  FROM outpatient_claims
  WHERE CLM_FROM_DT BETWEEN '2010-01-01' AND '2010-12-31'), 

-- Step 5: Combine all claims
all_claims AS (
  SELECT * FROM inpatient_costs
  UNION ALL
  SELECT * FROM outpatient_costs), 

-- Step 6: Aggregate by member and month
monthly_costs AS (
  SELECT 
    DESYNPUF_ID AS member_id,
    claim_month,
    claim_type,
    SUM(allowed_amount) AS total_monthly_cost
  FROM all_claims
  GROUP BY DESYNPUF_ID, claim_month, claim_type) 

-- Step 7: Join with member-months to compute PMPM
WITH ip AS(
SELECT
  mc.member_id,
  mc.claim_month,
  mc.claim_type,
  mc.total_monthly_cost,
  mm.months_enrolled
INTO monthly_member_cost
FROM monthly_costs mc
JOIN member_months mm ON mc.member_id = mm.DESYNPUF_ID
;


--Create combined claims table for Tableau export
--10,000 row limit
--only claims with dx & sx info

WITH ip AS(
SELECT
a.desynpuf_id
,clm_id
,'Inpatient' as claim_type
,clm_from_dt
,clm_thru_dt
,prvdr_num
,c.short_desc as state
,a.icd9_dgns_cd_1
,d.short_desc as diagnosis_1
,a.icd9_dgns_cd_2
,e.short_desc as diagnosis_2
,a.icd9_prcdr_cd_1
,f.short_desc as procedure_1
,a.icd9_prcdr_cd_2
,g.short_desc as procedure_2
,clm_pmt_amt
FROM inpatient_claims a
LEFT JOIN beneficiary_summary_10 b ON a.desynpuf_id = b.desynpuf_id
LEFT JOIN state_codes c ON b.sp_state_code = c.state_cd
LEFT JOIN dgns_codes d ON a.icd9_dgns_cd_1 = d.dgns_cd 
LEFT JOIN dgns_codes e ON a.icd9_dgns_cd_2 = e.dgns_cd 
LEFT JOIN prcdr_codes f ON a.icd9_prcdr_cd_1 = f.prcdr_cd 
LEFT JOIN prcdr_codes g ON a.icd9_prcdr_cd_2 = g.prcdr_cd 
WHERE clm_pmt_amt > 0
AND clm_from_dt >= '2010-01-01'
AND bene_hi_cvrage_tot_mons = 12
AND bene_smi_cvrage_tot_mons = 12
AND c.short_desc IS NOT NULL
AND c.short_desc != 'Others'
AND d.short_desc IS NOT NULL
order by random()
LIMIT 5000
),

op AS (
SELECT
a.desynpuf_id
,clm_id
,'Outpatient' as claim_type
,clm_from_dt
,clm_thru_dt
,prvdr_num
,c.short_desc as state
,a.icd9_dgns_cd_1
,d.short_desc as diagnosis_1
,a.icd9_dgns_cd_2
,e.short_desc as diagnosis_2
,a.icd9_prcdr_cd_1
,f.short_desc as procedure_1
,a.icd9_prcdr_cd_2
,g.short_desc as procedure_2
,clm_pmt_amt
FROM outpatient_claims a
LEFT JOIN beneficiary_summary_10 b ON a.desynpuf_id = b.desynpuf_id
LEFT JOIN state_codes c ON b.sp_state_code = c.state_cd
LEFT JOIN dgns_codes d ON a.icd9_dgns_cd_1 = d.dgns_cd
LEFT JOIN dgns_codes e ON a.icd9_dgns_cd_2 = e.dgns_cd
LEFT JOIN prcdr_codes f ON a.icd9_prcdr_cd_1 = f.prcdr_cd
LEFT JOIN prcdr_codes g ON a.icd9_prcdr_cd_2 = g.prcdr_cd
WHERE clm_pmt_amt > 0
AND clm_from_dt >= '2010-01-01'
AND bene_hi_cvrage_tot_mons = 12
AND bene_smi_cvrage_tot_mons = 12
AND c.short_desc IS NOT NULL
AND c.short_desc != 'Others'
AND d.short_desc IS NOT NULL
order by random()
LIMIT 5000
)

SELECT * FROM ip
UNION ALL
SELECT * FROM op
;